/* The following code was generated by JFlex 1.4.3 on 11/17/24, 8:20 PM */

package compilador;
import java.io.*;
import static compilador.Tokens.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/17/24, 8:20 PM from the specification file
 * <tt>C:/Users/Developer/OneDrive/Documentos/University/Archivos/PDF's/Autómatas/Programas/Compilador/src/compilador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\11\2\0\1\16\22\0\1\14\1\51\1\7\4\0"+
    "\1\12\1\52\1\53\1\20\1\6\1\44\1\2\1\4\1\17\12\3"+
    "\1\0\1\45\1\47\1\46\1\50\2\0\22\1\1\42\7\1\1\0"+
    "\1\10\2\0\1\1\1\0\1\24\1\36\1\22\1\31\1\5\1\13"+
    "\1\43\1\41\1\30\2\1\1\23\1\32\1\33\1\27\1\34\1\1"+
    "\1\37\1\25\1\40\1\35\1\26\1\56\3\1\1\54\1\0\1\55"+
    "\42\0\1\21\uff5f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\1\1\2\3\6\1\7\1\10\7\2\1\11"+
    "\1\12\1\13\1\14\1\15\1\1\1\16\1\17\1\20"+
    "\1\21\2\2\1\0\1\4\2\0\1\22\3\0\1\2"+
    "\1\23\1\0\3\2\1\24\6\2\1\25\1\26\1\27"+
    "\1\30\1\2\1\0\1\2\2\0\1\4\1\22\1\31"+
    "\1\0\1\2\2\0\3\2\1\32\6\2\1\0\1\2"+
    "\1\0\1\2\2\0\1\2\1\33\1\34\1\35\3\2"+
    "\1\36\2\2\1\0\1\37\1\23\1\40\2\2\1\41"+
    "\1\2\1\42\1\2\1\43\1\2\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\57\0\u011a"+
    "\0\57\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\57"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\57"+
    "\0\57\0\u03ac\0\u03db\0\u040a\0\u0439\0\57\0\57\0\57"+
    "\0\57\0\u0468\0\u0497\0\353\0\u04c6\0\u04f5\0\u011a\0\57"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u0497\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6"+
    "\0\57\0\57\0\57\0\57\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08a1\0\u011a\0\57\0\u08d0\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\u0497\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0497\0\u0497\0\u0497\0\u0c7c\0\u0cab\0\u0cda\0\u0497"+
    "\0\u0d09\0\u0d38\0\u0d67\0\u0497\0\57\0\u0497\0\u0d96\0\u0dc5"+
    "\0\u0497\0\u0df4\0\u0497\0\u0e23\0\u0497\0\u0e52\0\u0497\0\u0497";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\3\1\7\1\10"+
    "\1\2\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\2\1\21\3\3\1\22\1\3\1\23\1\3"+
    "\1\24\1\3\1\25\2\3\1\26\2\3\1\27\1\3"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\60\0\1\43\3\0\1\43\5\0"+
    "\1\43\6\0\22\43\12\0\1\43\3\0\1\5\1\44"+
    "\55\0\1\5\1\45\1\46\54\0\1\45\53\0\7\47"+
    "\1\50\1\51\46\47\10\52\1\53\1\52\1\0\44\52"+
    "\1\0\1\43\3\0\1\43\5\0\1\43\6\0\1\43"+
    "\1\54\20\43\12\0\1\43\14\0\1\14\57\0\1\15"+
    "\57\0\1\16\57\0\1\55\1\56\37\0\1\43\3\0"+
    "\1\43\5\0\1\43\6\0\1\43\1\57\15\43\1\60"+
    "\2\43\12\0\1\43\1\0\1\43\3\0\1\43\5\0"+
    "\1\43\6\0\5\43\1\61\14\43\12\0\1\43\1\0"+
    "\1\43\3\0\1\43\5\0\1\62\6\0\11\43\1\63"+
    "\10\43\12\0\1\43\1\0\1\43\3\0\1\43\5\0"+
    "\1\43\6\0\2\43\1\64\17\43\12\0\1\43\1\0"+
    "\1\43\3\0\1\43\5\0\1\43\6\0\13\43\1\65"+
    "\1\43\1\66\4\43\12\0\1\43\1\0\1\43\3\0"+
    "\1\67\5\0\1\43\6\0\22\43\12\0\1\43\1\0"+
    "\1\43\3\0\1\43\5\0\1\43\6\0\16\43\1\70"+
    "\3\43\12\0\1\43\46\0\1\71\56\0\1\72\56\0"+
    "\1\73\56\0\1\74\11\0\1\43\3\0\1\43\5\0"+
    "\1\43\6\0\17\43\1\75\2\43\12\0\1\43\1\0"+
    "\1\43\1\76\1\77\1\100\1\43\5\0\1\43\6\0"+
    "\22\43\12\0\1\43\3\0\1\45\1\0\1\46\53\0"+
    "\1\101\1\102\2\0\1\101\50\0\7\47\1\103\1\51"+
    "\46\47\12\0\1\104\54\0\1\105\47\0\1\43\1\76"+
    "\1\77\1\100\1\43\5\0\1\43\6\0\5\43\1\106"+
    "\14\43\12\0\1\43\11\55\1\0\45\55\20\107\1\110"+
    "\36\107\1\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\2\43\1\111\17\43\12\0\1\43\1\0"+
    "\1\43\1\76\1\77\1\100\1\43\5\0\1\43\6\0"+
    "\2\43\1\112\17\43\12\0\1\43\1\0\1\43\1\76"+
    "\1\77\1\100\1\43\5\0\1\43\6\0\6\43\1\113"+
    "\13\43\12\0\1\43\1\0\1\43\1\76\1\77\1\100"+
    "\1\43\5\0\1\43\6\0\16\43\1\114\3\43\12\0"+
    "\1\43\1\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\6\43\1\115\13\43\12\0\1\43\1\0"+
    "\1\43\1\76\1\77\1\100\1\43\5\0\1\43\6\0"+
    "\14\43\1\116\5\43\12\0\1\43\1\0\1\43\1\76"+
    "\1\77\1\100\1\43\5\0\1\43\6\0\6\43\1\117"+
    "\13\43\12\0\1\43\1\0\1\43\1\76\1\77\1\100"+
    "\1\43\5\0\1\43\6\0\2\43\1\120\17\43\12\0"+
    "\1\43\1\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\15\43\1\121\4\43\12\0\1\43\1\0"+
    "\1\43\1\76\1\77\1\100\1\43\5\0\1\43\6\0"+
    "\6\43\1\122\13\43\12\0\1\43\3\0\1\77\1\100"+
    "\53\0\1\123\1\0\1\77\1\124\1\125\5\0\1\123"+
    "\6\0\22\123\12\0\1\123\3\0\1\124\56\0\1\102"+
    "\63\0\1\52\1\0\2\52\17\0\1\52\2\0\3\52"+
    "\17\0\1\43\1\76\1\77\1\100\1\43\5\0\1\43"+
    "\6\0\2\43\1\126\17\43\12\0\1\43\20\107\1\127"+
    "\36\107\20\0\1\110\1\130\36\0\1\43\1\76\1\77"+
    "\1\100\1\43\5\0\1\43\6\0\3\43\1\131\16\43"+
    "\12\0\1\43\1\0\1\43\1\76\1\77\1\100\1\43"+
    "\5\0\1\43\6\0\15\43\1\132\4\43\12\0\1\43"+
    "\1\0\1\43\1\76\1\77\1\100\1\43\5\0\1\43"+
    "\6\0\7\43\1\133\12\43\12\0\1\43\1\0\1\43"+
    "\1\76\1\77\1\100\1\43\5\0\1\43\6\0\11\43"+
    "\1\134\10\43\12\0\1\43\1\0\1\43\1\76\1\77"+
    "\1\100\1\43\5\0\1\43\6\0\1\43\1\135\20\43"+
    "\12\0\1\43\1\0\1\43\1\76\1\77\1\100\1\43"+
    "\5\0\1\43\6\0\4\43\1\136\4\43\1\137\10\43"+
    "\12\0\1\43\1\0\1\43\1\76\1\77\1\100\1\43"+
    "\5\0\1\43\6\0\7\43\1\140\12\43\12\0\1\43"+
    "\1\0\1\43\1\76\1\77\1\100\1\43\5\0\1\43"+
    "\6\0\6\43\1\141\13\43\12\0\1\43\1\0\1\43"+
    "\1\76\1\77\1\100\1\43\5\0\1\43\6\0\1\43"+
    "\1\142\20\43\12\0\1\43\1\0\1\123\1\76\1\77"+
    "\1\100\1\123\5\0\1\123\6\0\22\123\12\0\1\123"+
    "\1\0\1\123\1\0\1\124\1\0\1\125\5\0\1\123"+
    "\6\0\22\123\12\0\1\123\1\0\1\123\1\76\1\77"+
    "\1\100\1\123\1\143\4\0\1\123\6\0\22\123\12\0"+
    "\1\123\1\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\16\43\1\144\3\43\12\0\1\43\17\107"+
    "\1\145\1\127\36\107\17\0\1\145\40\0\1\43\1\76"+
    "\1\77\1\100\1\43\5\0\1\43\6\0\3\43\1\146"+
    "\16\43\12\0\1\43\1\0\1\43\1\76\1\77\1\100"+
    "\1\43\5\0\1\43\6\0\6\43\1\147\13\43\12\0"+
    "\1\43\1\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\2\43\1\150\17\43\12\0\1\43\1\0"+
    "\1\43\1\76\1\77\1\100\1\43\5\0\1\43\6\0"+
    "\16\43\1\151\3\43\12\0\1\43\1\0\1\43\1\76"+
    "\1\77\1\100\1\43\5\0\1\43\6\0\11\43\1\152"+
    "\10\43\12\0\1\43\1\0\1\43\1\76\1\77\1\100"+
    "\1\153\5\0\1\43\6\0\22\43\12\0\1\43\3\0"+
    "\1\154\54\0\1\43\1\76\1\77\1\100\1\43\5\0"+
    "\1\43\6\0\1\155\21\43\12\0\1\43\1\0\1\43"+
    "\1\76\1\77\1\100\1\43\5\0\1\43\6\0\16\43"+
    "\1\156\3\43\12\0\1\43\1\0\1\43\1\76\1\77"+
    "\1\100\1\43\5\0\1\43\6\0\21\43\1\157\12\0"+
    "\1\43\1\0\1\123\1\0\1\154\1\0\1\123\5\0"+
    "\1\123\6\0\22\123\12\0\1\123\1\0\1\43\1\76"+
    "\1\77\1\100\1\160\5\0\1\43\6\0\22\43\12\0"+
    "\1\43";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3713];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\1\11\6\1\1\11"+
    "\7\1\2\11\4\1\4\11\2\1\1\0\1\1\2\0"+
    "\1\11\3\0\2\1\1\0\12\1\4\11\1\1\1\0"+
    "\1\1\2\0\2\1\1\11\1\0\1\1\2\0\12\1"+
    "\1\0\1\1\1\0\1\1\2\0\12\1\1\0\1\1"+
    "\1\11\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    Analisis c=new Analisis();
    int estado = 0;
    int nu=0;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { c.linea = yyline; lexeme = yytext(); return close_key;
          }
        case 38: break;
        case 10: 
          { c.linea= yyline; estado = 0; lexeme = yytext(); return semicolon;
          }
        case 39: break;
        case 13: 
          { c.linea = yyline; lexeme = yytext(); return greater_than;
          }
        case 40: break;
        case 3: 
          { c.linea= yyline; lexeme = yytext(); return minus;
          }
        case 41: break;
        case 18: 
          { c.linea = yyline; lexeme = yytext(); return litcad;
          }
        case 42: break;
        case 32: 
          { c.linea = yyline; lexeme = yytext(); return classType;
          }
        case 43: break;
        case 11: 
          { c.linea= yyline; lexeme = yytext(); return equal;
          }
        case 44: break;
        case 31: 
          { estado = 2; c.linea = yyline; lexeme = yytext(); return floatType;
          }
        case 45: break;
        case 12: 
          { c.linea = yyline; lexeme = yytext(); return less_than;
          }
        case 46: break;
        case 9: 
          { c.linea= yyline; lexeme = yytext(); return coma;
          }
        case 47: break;
        case 14: 
          { c.linea = yyline; lexeme = yytext(); return open_parenth;
          }
        case 48: break;
        case 30: 
          { c.linea = yyline; lexeme = yytext(); return read;
          }
        case 49: break;
        case 23: 
          { c.linea = yyline; lexeme = yytext(); return greater_or_equals;
          }
        case 50: break;
        case 19: 
          { /* Ignore */
          }
        case 51: break;
        case 37: 
          { c.linea = yyline; lexeme = yytext(); return privateType;
          }
        case 52: break;
        case 28: 
          { c.linea = yyline; lexeme = yytext(); return voidType;
          }
        case 53: break;
        case 22: 
          { c.linea = yyline; lexeme = yytext(); return less_or_equals;
          }
        case 54: break;
        case 27: 
          { estado = 3; c.linea = yyline; lexeme = yytext(); return charType;
          }
        case 55: break;
        case 36: 
          { estado = 4; c.linea= yyline; lexeme = yytext(); return stringType;
          }
        case 56: break;
        case 25: 
          { c.linea = yyline; lexeme = yytext(); return litcar;
          }
        case 57: break;
        case 7: 
          { c.linea= yyline; lexeme = yytext(); return div;
          }
        case 58: break;
        case 35: 
          { c.linea = yyline; lexeme = yytext(); return publicType;
          }
        case 59: break;
        case 34: 
          { c.linea = yyline; lexeme = yytext(); return while_keyword;
          }
        case 60: break;
        case 16: 
          { c.linea = yyline; lexeme = yytext(); return open_key;
          }
        case 61: break;
        case 4: 
          { c.linea = yyline; lexeme = yytext(); return num;
          }
        case 62: break;
        case 29: 
          { c.linea = yyline; lexeme = yytext(); return mainType;
          }
        case 63: break;
        case 5: 
          { c.linea= yyline; lexeme = yytext(); return plus;
          }
        case 64: break;
        case 2: 
          { if(estado == 1) {
        c.linea = yyline;
        lexeme = yytext();
        return idI;
    } else if(estado == 2) {
        c.linea = yyline;
        lexeme = yytext();
        return idF;
    } else if(estado == 3) {
        c.linea = yyline;
        lexeme = yytext();
        return idC;
    } else if(estado == 4) {
        c.linea = yyline;
        lexeme = yytext();
        return idS;
    } else {
        lexeme = yytext();
        return id;
    }
          }
        case 65: break;
        case 33: 
          { c.linea = yyline; lexeme = yytext(); return print;
          }
        case 66: break;
        case 24: 
          { c.linea = yyline; lexeme = yytext(); return different_to;
          }
        case 67: break;
        case 1: 
          { c.linea = yyline; lexeme = yytext(); return Error;
          }
        case 68: break;
        case 26: 
          { estado = 1; c.linea = yyline; lexeme = yytext(); return intType;
          }
        case 69: break;
        case 21: 
          { c.linea = yyline; lexeme = yytext(); return equals_to;
          }
        case 70: break;
        case 20: 
          { c.linea = yyline; lexeme = yytext(); return if_keyword;
          }
        case 71: break;
        case 15: 
          { c.linea = yyline; lexeme = yytext(); return close_parenth;
          }
        case 72: break;
        case 8: 
          { c.linea= yyline; lexeme = yytext(); return mult;
          }
        case 73: break;
        case 6: 
          { /*Ignore*/
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            c.linea = yyline; lexeme = yytext(); return Error;
          }
      }
    }
  }


}
